/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Paquete_POO.*;
import javax.swing.JOptionPane;
/**
 *
 * @author crisv
 */
public class FrmGestionPedidos extends javax.swing.JFrame {
private GestionPedidos gestionPedidos;
private GestionClientes gestionClientes;
private GestionMenu gestionMenu;
private Detalle_Pedido[] detallesActuales;
private int cantDetalles;
private javax.swing.table.DefaultTableModel modeloProductos;
private javax.swing.table.DefaultTableModel modeloCombos;
private javax.swing.table.DefaultTableModel modeloPedidos;
private GestionEmpleados gestionEmpleados;
    /**
     * Creates new form FrmGestionPedidos
     */
public FrmGestionPedidos() {

    initComponents();
    
    detallesActuales = new Detalle_Pedido[50];
    cantDetalles = 0;

    gestionPedidos = Sistema.gestionPedidos;
    gestionMenu = Sistema.gestionMenu;
    gestionClientes = Sistema.gestionClientes;
    gestionEmpleados = Sistema.gestionEmpleados;



    modeloProductos = new javax.swing.table.DefaultTableModel();

    modeloProductos.addColumn("Código");
    modeloProductos.addColumn("Nombre");
    modeloProductos.addColumn("Precio");

    tablaProductos.setModel(modeloProductos);



    modeloCombos = new javax.swing.table.DefaultTableModel();

    modeloCombos.addColumn("Código");
    modeloCombos.addColumn("Nombre");
    modeloCombos.addColumn("Precio");

    tablaCombos.setModel(modeloCombos);

    modeloPedidos = new javax.swing.table.DefaultTableModel();

modeloPedidos.addColumn("Número");
modeloPedidos.addColumn("Cliente");
modeloPedidos.addColumn("Tipo Entrega");
modeloPedidos.addColumn("Estado");

tablaPedidos.setModel(modeloPedidos);
    
    cargarProductos();
    cargarCombos();
    cargarPedidos();


}

private void cargarProductos(){

    modeloProductos.setRowCount(0);

    for(int i = 0; i < gestionMenu.getCantProductos(); i++){

        Producto p = gestionMenu.getListaProductos()[i];

        modeloProductos.addRow(new Object[]{
            p.getCodigo(),
            p.getNombre(),
            p.getPrecioBase()
        });
    }
}
private void cargarCombos(){

    modeloCombos.setRowCount(0);

    for(int i = 0; i < gestionMenu.getCantCombos(); i++){

        Combo c = gestionMenu.getListaCombos()[i];

        modeloCombos.addRow(new Object[]{
            c.getCodigo(),
            c.getNombre(),
            c.getPrecioPromocional()
        });
    }
}

private void cargarPedidos(){

    modeloPedidos.setRowCount(0);

    for(int i = 0; i < gestionPedidos.getCantPedidos(); i++){

        Pedido p = gestionPedidos.getListaPedidos()[i];

        modeloPedidos.addRow(new Object[]{
            p.getNumero(),
            p.getCliente().getNombres(),
            p.getTipoEntrega(),
            p.getEstado()
        });
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        txtDNI = new javax.swing.JTextField();
        cmbTipoEntrega = new javax.swing.JComboBox<>();
        cmbEstado = new javax.swing.JComboBox<>();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnEstado = new javax.swing.JButton();
        btnFactura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCombos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnVolver = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaPedidos = new javax.swing.JTable();
        btnAgregarProducto = new javax.swing.JButton();
        btnAgregarCombo = new javax.swing.JButton();
        btnAsignarRepartidor = new javax.swing.JButton();
        btnRecargo = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRecargo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestion de Pedidos");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("GESTION DE PEDIDOS");

        jLabel2.setText("Número de pedido:");

        jLabel3.setText("DNI cliente:");

        jLabel4.setText("Tipo entrega:");

        jLabel5.setText("Estado");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        txtDNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNIActionPerformed(evt);
            }
        });

        cmbTipoEntrega.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Delivery", "Recojo en Tienda", " " }));
        cmbTipoEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoEntregaActionPerformed(evt);
            }
        });

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "En cocina", "Enviado", "Entregado", " ", " " }));
        cmbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEstadoActionPerformed(evt);
            }
        });

        btnCrear.setText("Crear pedido");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEstado.setText("Actualizar Estado");
        btnEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadoActionPerformed(evt);
            }
        });

        btnFactura.setText("Generar Factura");
        btnFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturaActionPerformed(evt);
            }
        });

        tablaCombos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tablaCombos);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Codigo", "Nombre", "Precio"
            }
        ));
        jScrollPane2.setViewportView(tablaProductos);

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        tablaPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Número", "Cliente", "Tipo entrega", "Estado"
            }
        ));
        jScrollPane3.setViewportView(tablaPedidos);

        btnAgregarProducto.setText("Agregar producto");
        btnAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProductoActionPerformed(evt);
            }
        });

        btnAgregarCombo.setText("Agregar Combo");
        btnAgregarCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarComboActionPerformed(evt);
            }
        });

        btnAsignarRepartidor.setText("Asignar Repartidor");
        btnAsignarRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarRepartidorActionPerformed(evt);
            }
        });

        btnRecargo.setText("Recargo Ruta");
        btnRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargoActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado");

        txtRecargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRecargoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEstado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCrear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAsignarRepartidor, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAgregarProducto))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnVolver)
                                    .addComponent(btnAgregarCombo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipoEntrega, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDNI)
                            .addComponent(txtNumero)
                            .addComponent(cmbEstado, 0, 150, Short.MAX_VALUE)
                            .addComponent(txtRecargo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(cmbTipoEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRecargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear)
                            .addComponent(btnBuscar)
                            .addComponent(btnAgregarProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEstado)
                            .addComponent(btnFactura)
                            .addComponent(btnAgregarCombo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVolver)
                            .addComponent(btnAsignarRepartidor)
                            .addComponent(btnRecargo))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void txtDNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNIActionPerformed

    private void cmbTipoEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoEntregaActionPerformed

    private void cmbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEstadoActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        // TODO add your handling code here:
        int dni = Integer.parseInt(txtDNI.getText());


Cliente cliente = gestionClientes.buscarCliente(dni);


if(cliente != null){


    int numero = gestionPedidos.generarNumeroPedido();


    String tipoEntrega = cmbTipoEntrega.getSelectedItem().toString();



    Pedido pedido = new Pedido();
    


    pedido.setNumero(numero);

    pedido.setCliente(cliente);

    pedido.setTipoEntrega(tipoEntrega);

    pedido.setEstado("En Cocina");


    pedido.setDetalles(detallesActuales);



    if(gestionPedidos.crearPedido(pedido)){


        javax.swing.JOptionPane.showMessageDialog(this,
                "Pedido creado correctamente");


        txtNumero.setText(String.valueOf(numero));
        cargarPedidos();

        cantDetalles = 0;
         

    }



}else{


    javax.swing.JOptionPane.showMessageDialog(this,
            "Cliente no encontrado");

}

    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(txtNumero.getText());

Pedido pedido = gestionPedidos.buscarPedido(numero);

if(pedido != null){

    cmbEstado.setSelectedItem(pedido.getEstado());
    cmbTipoEntrega.setSelectedItem(pedido.getTipoEntrega());

    JOptionPane.showMessageDialog(this, "Pedido encontrado");

}else{

    JOptionPane.showMessageDialog(this, "Pedido no encontrado");

}
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadoActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(txtNumero.getText());

String estado = cmbEstado.getSelectedItem().toString();

gestionPedidos.actualizarEstado(numero, estado);

cargarPedidos();

JOptionPane.showMessageDialog(this, "Estado actualizado");

Pedido pedido = gestionPedidos.buscarPedido(numero);

if(estado.equals("Entregado")){

    if(pedido.getRepartidor() != null){

        pedido.getRepartidor().setDisponible(true);

    }

}
    }//GEN-LAST:event_btnEstadoActionPerformed

    private void btnFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturaActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(txtNumero.getText());

Factura factura = gestionPedidos.generarComprobante(numero);

if(factura != null){

    JOptionPane.showMessageDialog(this,
            "Factura generada\n\n"
            + "Subtotal: " + factura.getSubtotal()
            + "\nIGV: " + factura.getIgv()
            + "\nTotal: " + factura.getTotal());

}else{

    JOptionPane.showMessageDialog(this,
            "Pedido no encontrado");

}
    }//GEN-LAST:event_btnFacturaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProductoActionPerformed
        // TODO add your handling code here:
        int fila = tablaProductos.getSelectedRow();


if(fila == -1){

    javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un producto");

    return;
}



int codigo = Integer.parseInt(
        tablaProductos.getValueAt(fila, 0).toString()
);



Producto producto = gestionMenu.buscarProducto(codigo);



if(producto != null){


    String cantidadTexto = javax.swing.JOptionPane.showInputDialog(
            this,
            "Ingrese cantidad:"
    );


    int cantidad = Integer.parseInt(cantidadTexto);



    Detalle_Pedido detalle = new Detalle_Pedido(
            producto,
            null,
            cantidad
    );



    detallesActuales[cantDetalles] = detalle;

    cantDetalles++;



    javax.swing.JOptionPane.showMessageDialog(this,
            "Producto agregado al pedido");

}
    }//GEN-LAST:event_btnAgregarProductoActionPerformed

    private void btnAgregarComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarComboActionPerformed
        // TODO add your handling code here:
        int fila = tablaCombos.getSelectedRow();


if(fila == -1){

    javax.swing.JOptionPane.showMessageDialog(this,
            "Seleccione un combo");

    return;
}



int codigo = Integer.parseInt(
        tablaCombos.getValueAt(fila, 0).toString()
);



Combo combo = gestionMenu.buscarCombo(codigo);



if(combo != null){


    String cantidadTexto = javax.swing.JOptionPane.showInputDialog(
            this,
            "Ingrese cantidad:"
    );


    int cantidad = Integer.parseInt(cantidadTexto);



    Detalle_Pedido detalle = new Detalle_Pedido(
            null,
            combo,
            cantidad
    );



    detallesActuales[cantDetalles] = detalle;

    cantDetalles++;



    javax.swing.JOptionPane.showMessageDialog(this,
            "Combo agregado al pedido");

}
    }//GEN-LAST:event_btnAgregarComboActionPerformed

    private void btnAsignarRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarRepartidorActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(txtNumero.getText());

Pedido pedido = gestionPedidos.buscarPedido(numero);

if(pedido == null){
    JOptionPane.showMessageDialog(this, "Pedido no encontrado");
    return;
}

if(!pedido.getTipoEntrega().equals("Delivery")){
    JOptionPane.showMessageDialog(this, "Este pedido no es Delivery");
    return;
}

Repartidor rep = gestionEmpleados.buscarRepartidorDisponible();

if(rep == null){
    JOptionPane.showMessageDialog(this, "No hay repartidores disponibles");
    return;
}

gestionPedidos.asignarRepartidor(numero, rep);

JOptionPane.showMessageDialog(this,
        "Repartidor asignado: " + rep.getNombres());

cargarPedidos();
    }//GEN-LAST:event_btnAsignarRepartidorActionPerformed

    private void btnRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargoActionPerformed
        // TODO add your handling code here:
        int numero = Integer.parseInt(txtNumero.getText());

    float monto = Float.parseFloat(txtRecargo.getText());


    gestionPedidos.agregarRecargoRuta(numero, monto);


    JOptionPane.showMessageDialog(this,
            "Recargo agregado correctamente");
    }//GEN-LAST:event_btnRecargoActionPerformed

    private void txtRecargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRecargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRecargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGestionPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmGestionPedidos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCombo;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAsignarRepartidor;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnEstado;
    private javax.swing.JButton btnFactura;
    private javax.swing.JButton btnRecargo;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbTipoEntrega;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaCombos;
    private javax.swing.JTable tablaPedidos;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtDNI;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtRecargo;
    // End of variables declaration//GEN-END:variables
}
