/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ventana;
import Paquete_POO.*;
/**
 *
 * @author crisv
 */
public class FrmReportes extends javax.swing.JFrame {
private GestionPedidos gestionPedidos;
private GestionEmpleados gestionEmpleados;
    /**
     * Creates new form FrmReportes
     */
    public FrmReportes() {
        initComponents();
        
    gestionPedidos = Sistema.gestionPedidos;
    gestionEmpleados = Sistema.gestionEmpleados;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProductividad = new javax.swing.JButton();
        btnIngresos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReporte = new javax.swing.JTextArea();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProductividad.setText("Reporte Productividad");
        btnProductividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductividadActionPerformed(evt);
            }
        });

        btnIngresos.setText("Reporte Ingresos");
        btnIngresos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresosActionPerformed(evt);
            }
        });

        txtReporte.setColumns(20);
        txtReporte.setRows(5);
        jScrollPane1.setViewportView(txtReporte);

        btnVolver.setText("Volver");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btnProductividad)))
                .addContainerGap(42, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresos)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnVolver)
                        .addGap(25, 25, 25)))
                .addGap(237, 237, 237))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnProductividad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIngresos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnVolver)
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresosActionPerformed
        // TODO add your handling code here:
                                         

    float totalIngresos = 0;
    int cantidadPedidos = 0;


    for(int i = 0; i < gestionPedidos.getCantPedidos(); i++){

        Pedido ped = gestionPedidos.getListaPedidos()[i];


        if(ped != null){

            if(ped.getFactura() != null){

                totalIngresos += ped.getFactura().getTotal();

                cantidadPedidos++;

            }

        }

    }


    txtReporte.setText(
            "REPORTE DE INGRESOS\n\n"
            + "Pedidos facturados: " + cantidadPedidos
            + "\nIngresos totales: S/ " + totalIngresos
    );

    }//GEN-LAST:event_btnIngresosActionPerformed

    private void btnProductividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductividadActionPerformed
        // TODO add your handling code here:
                                                

    int pedidosTotales = gestionPedidos.getCantPedidos();

    String reporte = "REPORTE DE PRODUCTIVIDAD\n\n";

    reporte += "Pedidos registrados: " + pedidosTotales + "\n\n";


    reporte += "ENTREGAS POR REPARTIDOR:\n";


    for(int i = 0; i < gestionEmpleados.getCantEmpleados(); i++){

        Empleado emp = gestionEmpleados.getListaEmpleados()[i];


        if(emp instanceof Repartidor){

            Repartidor rep = (Repartidor) emp;

            int entregas = 0;


            for(int j = 0; j < gestionPedidos.getCantPedidos(); j++){

                Pedido ped = gestionPedidos.getListaPedidos()[j];


                if(ped.getRepartidor() != null &&
                   ped.getRepartidor().getDni() == rep.getDni()){

                    if(ped.getEstado().equals("Entregado")){

                        entregas++;

                    }
                }

            }


            reporte += rep.getNombres()
                    + " : "
                    + entregas
                    + " entregas\n";

        }

    }


    txtReporte.setText(reporte);


    }//GEN-LAST:event_btnProductividadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmReportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmReportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresos;
    private javax.swing.JButton btnProductividad;
    private javax.swing.JButton btnVolver;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtReporte;
    // End of variables declaration//GEN-END:variables
}
